### ISSUE TITLE
Core UI Rage: Proposal Details Schema

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#31]
## What

- Define initial json schema for proposal details
- Implement in the proposal form
- Display in proposal details
- Explore parsing in subgraph

### Details/Notes

schema idea:

```javascript
const details = {
  title: 'prop 1',
  description: 'a quick description',
  contentURI: 'used to be link field, could be a link to a forum post, more description, ipfs anything, whatevs.',
  contentURIType: 'link, ipfs, list',
  proposalType: 'member'
}
```

- Note: the contentURI field name is from the daostar standard.

#### Questions to explore
- I feel the most work needs to be done around standardizing the proposalType field somewhat. Might even need to define base proposal types we'll offer + guidance and making new ones?
- How will we display a proposal that doesn't conform to our schema? this could be an indication the prop wasn't created in our UI.

**Comment by jordanlesich** [comment]
Took some time to get the model inside of Tyoescript to see what we could do to enforce types
```js
export const PROPOSAL_TYPES = {
  FREE: 'Free Shit Proposal',
} as const;
export const CONTENT_TYPES = {
  LINK: 'link',
  LINKS: 'arrayOfLinks',
  MD: 'markdown',
  PINATA_MD: 'pinataMarkdown',
} as const;

type ValueOf<T> = T[keyof T];

type ContentURI = {
  type: ValueOf<typeof CONTENT_TYPES>;
  content: string | ContentURI[];
  [index: string]: unknown;
};

type ProposalDetails = {
  title: string;
  proposalType: ValueOf<typeof PROPOSAL_TYPES>;
  description?: string;
  contentURI: ContentURI | undefined;
};
````
## ValueOf

The ValueOf type gets an Object dictionary and use the Object's values as an enumerator. I could have used the TS enumerator, but I couldn't find a way to turn an existing object into an enumerator (crazy considering how common this pattern is). 

Using this pattern allows us to use TS to guard against proposal or content types that don't exist.  

So now we can (soft) enforce the details model using this function 

```js
const createProposalDetails = (detailsObject: ProposalDetails) =>
  JSON.stringify({
    ...detailsObject,
    contentURI: JSON.stringify(detailsObject.contentURI),
  });
```
And passing in data that is shaped like this. 

```js
const proposaDetails = createProposalDetails({
  title: '20 Share Giveaway',
  description: 'Give 20 share to some random address',
  contentURI: {
    type: CONTENT_TYPES.LINK,
    content: 'https://www.twistedchickentenders.com/',
  },
  proposalType: PROPOSAL_TYPES.FREE,
});
```

## Deviations: 

- ContentURIType shouldn't be its own field imo. The content and the type should exist in one field so that anyone can we handle any content type with any extra data that it needs all in one field. 

## Questions 

- Should we add the ability for devs to add extra data to the type so that it's more flexible? Ex. 
```js
type ProposalDetails = {
  title: string;
  proposalType: ValueOf<typeof PROPOSAL_TYPES>;
  description?: string;
  contentURI: ContentURI | undefined;
  [wildcard: index]: string
};


```
Doing so would ensure that we're still getting the data we need, while adding flexibility. However is flexibility good in this case?

**Comment by skuhlmann** [comment]
- agree on the contentURI structure
- [wildcard: index]: string - I think this is good to allow flexibility here. I don't really see the downside of extra stuff getting added. we won't deal with parsing anything in the subgraph except the 4 we're supporting.

**Comment by skuhlmann** [comment]
Have run into issues with storing the nested contentURI. So we've implemented as

```
const proposaDetails = createProposalDetails({
  title: '20 Share Giveaway',
  description: 'Give 20 share to some random address',
  contentURI: 'https://www.twistedchickentenders.com/',
  contentURIType: 'link',
  proposalType: PROPOSAL_TYPES.FREE,
});
```

**Comment by skuhlmann** [comment]
added:

```
    title
    description
    contentURI
    contentURIType
    ```
    
    to the subgraph
