### ISSUE TITLE
Monorepo CI Setup

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#8]
- Get working for:
  - rage react apps
  - 1st version of rage libraries to npm
  - subgraphs
  - lambdas

deployment pipelines

- gh actions for skynet deployment
- domains alpha.summon.daohaus.club / alpha.hub.daohaus.club
- gh actions for npm deployment
- gh actions for subgraph deployment
- gh action for serverless lambda deployment

--- 

- [ ] Subgraph local development
- [ ] Hardhat local development
- [ ] Package Publishing

**Comment by alexkeating** [comment]
Since Subgraph is a separate ticket now I can wrap this up with a lambda and library example. @skuhlmann would taking the lambda example we did at EthDenver and publishing an initial alpha for the data library be suffcient to move this to done. Or should I wait for some rages to make it through the pipeline

**Comment by skuhlmann** [comment]
@alexkeating 

Yeah I think that is perfect. Let's move on.
